<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'agents-manager',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.9.11-alpha1784214611',
    ),
    'jetpack-agents-manager' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-agents-manager',
      'ver' => '0.8.2-alpha1784214611',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.4.6-alpha1784214611',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '8.7.9-alpha1784214611',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.5.0',
    ),
  ),
);
