<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'agents-manager',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.9.2',
    ),
    'jetpack-agents-manager' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-agents-manager',
      'ver' => '0.5.0-alpha1781563708',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.43',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '8.7.0-alpha1781554849',
    ),
  ),
);
